apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.host }}
  labels:
    app: service-exchange
    tier: db
    version: {{ .Values.version }}
spec:
  selector:
    app: service-exchange
    tier: db
  ports:
  - name: tcp
    protocol: TCP
    port: {{ .Values.mysql.service_port }}
    targetPort: {{ .Values.mysql.backend_port }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: service-exchange-db-pvc
  labels:
    app: service-exchange
    tier: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: service-exchange-db-deployment
  labels:
    app: service-exchange
    tier: db
    version: {{ .Values.version }}
spec:
  selector:
    matchLabels:
      app: service-exchange
      tier: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: service-exchange
        tier: db
        version: {{ .Values.version }}
    spec:
      containers:
      - name: service-exchange-db
        image: mysql:8.0.11
        imagePullPolicy: IfNotPresent
        lifecycle:
          postStart:
            exec:
              command: ["sh", "-c", "rm -rf /var/lib/mysql/lost+found"]
        args:
          - --default-authentication-plugin=mysql_native_password
          - --binlog-expire-logs-seconds=604800
          - --max-binlog-size=1073741824
        env:
          # $ kubectl create secret generic mysql-pass --from-file=password.txt
          # make sure password.txt does not have a trailing newline
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password.txt
              name: mysql-pass
        - name: MYSQL_ROOT_HOST
          value: "%"
        ports:
        - containerPort: {{ .Values.mysql.backend_port }}
          name: mysql
        volumeMounts:
        - name: db-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: db-persistent-storage
        persistentVolumeClaim:
          claimName: service-exchange-db-pvc
